import type {
  Allocation,
  Badge,
  BoatTrip,
  DirectoryEntry,
  EmergencyResponder,
  GearItem,
  HazardPin,
  Island,
  IslandDistress,
  MicroMarket,
  Post,
  TideLog,
  TradeRequest,
  WeatherAlert,
  WorkParty,
} from "./types";

export const HOME_ISLAND = "Cedar Cove";

export const posts: Post[] = [
  {
    id: "p1",
    author: "Mara K.",
    householdId: "HH-1042",
    island: "Cedar Cove",
    scope: "my-isle",
    tag: "ResourceOffer",
    title: "Extra diesel — 20L available",
    body: "Storm generator ran less than expected. Diesel in sealed jerry cans at Dock 2. First come for neighbors only.",
    action: "I Can Help",
    actionCount: 3,
    image: "/posts/diesel.png",
    createdAt: "2026-08-30T08:15:00Z",
    comments: [
      { id: "c1", author: "Jonas P.", body: "Taking 5L for the pump — thank you Mara.", createdAt: "2026-08-30T08:31:00Z" },
      { id: "c2", author: "Elena R.", body: "Cans are sealed and dated, all good.", createdAt: "2026-08-30T08:52:00Z" },
    ],
  },
  {
    id: "p2",
    author: "Jonas P.",
    householdId: "HH-0871",
    island: "Cedar Cove",
    scope: "my-isle",
    tag: "HazardAlert",
    title: "Downed line on North Trail",
    body: "Power line across footpath near the cedar grove. Avoid until utility crew clears — ETA noon.",
    action: "I Can Help",
    actionCount: 7,
    image: "/posts/hazard.png",
    createdAt: "2026-08-30T07:40:00Z",
    isUrgent: true,
    comments: [
      { id: "c3", author: "Tui M.", body: "Cones out at both trail ends.", createdAt: "2026-08-30T07:58:00Z" },
      { id: "c4", author: "Dock Crew", body: "Utility crew confirmed for noon.", createdAt: "2026-08-30T08:20:00Z" },
    ],
  },
  {
    id: "p3",
    author: "Elena R.",
    householdId: "HH-1203",
    island: "Cedar Cove",
    scope: "my-isle",
    tag: "FairShare",
    title: "Storm kit allocation open",
    body: "Households HH-1000–HH-1300 can reserve one storm kit per family. Pickup at High-Ground Hub when ferry docks.",
    action: "Claim Allocation",
    actionCount: 12,
    image: "/posts/supplies.png",
    createdAt: "2026-08-30T06:00:00Z",
    comments: [
      { id: "c5", author: "Hana W.", body: "One kit per household, no exceptions this round.", createdAt: "2026-08-30T06:35:00Z" },
    ],
  },
  {
    id: "p4",
    author: "Tui M.",
    householdId: "HH-0550",
    island: "Cedar Cove",
    scope: "my-isle",
    tag: "RideShare",
    title: "Truck run to mainland Saturday",
    body: "Heading to Port Alton for supplies. Two cargo spots and one passenger seat. Return Sunday AM.",
    action: "Hop on Boat",
    actionCount: 2,
    createdAt: "2026-08-29T18:30:00Z",
  },
  {
    id: "p5",
    author: "Hana W.",
    householdId: "HH-0334",
    island: "Cedar Cove",
    scope: "my-isle",
    tag: "LocalMarket",
    title: "Smoked salmon — dockside today",
    body: "Fresh catch smoked this morning. $18/lb at the old fish shed. Barter welcome for firewood.",
    action: "I Can Help",
    actionCount: 5,
    image: "/posts/salmon.png",
    createdAt: "2026-08-30T09:00:00Z",
    comments: [
      { id: "c6", author: "Mara K.", body: "Trading a cord of cedar for two lbs.", createdAt: "2026-08-30T09:24:00Z" },
    ],
  },
  {
    id: "p6",
    author: "Keoni L.",
    householdId: "HH-2201",
    island: "Driftwood Atoll",
    scope: "archipelago",
    tag: "ResourceOffer",
    title: "Water filters surplus (12 units)",
    body: "Our shipment doubled. Happy to trade for fuel or boat parts. Can meet mid-channel Thursday.",
    action: "I Can Help",
    actionCount: 4,
    createdAt: "2026-08-30T05:20:00Z",
  },
  {
    id: "p7",
    author: "Sofia N.",
    householdId: "HH-4410",
    island: "Saltwind Cay",
    scope: "archipelago",
    tag: "HazardAlert",
    title: "Erosion at south landing",
    body: "South dock approach washed out overnight. Use east cove until repairs complete.",
    action: "I Can Help",
    actionCount: 9,
    createdAt: "2026-08-29T22:10:00Z",
    isUrgent: true,
    comments: [
      { id: "c7", author: "Keoni L.", body: "Sandbags on the way from Driftwood.", createdAt: "2026-08-29T23:02:00Z" },
      { id: "c8", author: "Ravi S.", body: "Our survey crew can look Thursday.", createdAt: "2026-08-30T01:15:00Z" },
    ],
  },
  {
    id: "p8",
    author: "Ravi S.",
    householdId: "HH-7788",
    island: "Farreach Isle",
    scope: "archipelago",
    tag: "LocalMarket",
    title: "Micro-market: honey & herbs",
    body: "Pop-up at community hall steps. Wildflower honey, dried kelp seasoning. Today until 4pm.",
    action: "I Can Help",
    actionCount: 1,
    createdAt: "2026-08-30T10:00:00Z",
  },
  {
    id: "p9",
    author: "Noa T.",
    householdId: "HH-0198",
    island: "Cedar Cove",
    scope: "my-isle",
    tag: "ResourceOffer",
    title: "Spare propane canisters \u2014 4 left",
    body: "Cleared out the shed after the refit. Half-full canisters, good for camp stoves. Porch pickup, no need to knock.",
    action: "I Can Help",
    actionCount: 6,
    createdAt: "2026-08-30T07:05:00Z",
  },
  {
    id: "p10",
    author: "Beatriz A.",
    householdId: "HH-1177",
    island: "Cedar Cove",
    scope: "my-isle",
    tag: "RideShare",
    title: "School run to High-Ground Hub",
    body: "Taking the flatbed up at 07:30 each morning while the low road floods. Four seats, dry gear provided.",
    action: "Hop on Boat",
    actionCount: 11,
    createdAt: "2026-08-30T06:45:00Z",
    comments: [
      { id: "c9", author: "Tui M.", body: "Two of mine on Wednesday if there is room.", createdAt: "2026-08-30T07:12:00Z" },
    ],
  },
  {
    id: "p11",
    author: "Dock Crew",
    householdId: "HH-0002",
    island: "Cedar Cove",
    scope: "my-isle",
    tag: "HazardAlert",
    title: "Loose planking, Dock 3 west finger",
    body: "Two boards lifted in the swell overnight. Flagged with orange tape \u2014 keep children off until we re-bolt at low tide.",
    action: "I Can Help",
    actionCount: 8,
    image: "/posts/hazard.png",
    createdAt: "2026-08-30T05:50:00Z",
    isUrgent: true,
  },
  {
    id: "p12",
    author: "Amara O.",
    householdId: "HH-0620",
    island: "Cedar Cove",
    scope: "my-isle",
    tag: "FairShare",
    title: "Drinking water ration \u2014 second window",
    body: "Cistern levels recovered enough for a second draw. Households HH-0500\u2013HH-0900 may claim 20L each through Sunday.",
    action: "Claim Allocation",
    actionCount: 17,
    image: "/posts/supplies.png",
    createdAt: "2026-08-30T04:30:00Z",
    comments: [
      { id: "c10", author: "Noa T.", body: "Claimed \u2014 collecting after the tide turns.", createdAt: "2026-08-30T05:02:00Z" },
    ],
  },
  {
    id: "p13",
    author: "Wen L.",
    householdId: "HH-0912",
    island: "Cedar Cove",
    scope: "my-isle",
    tag: "LocalMarket",
    title: "Sourdough + kelp butter, village square",
    body: "Baked eight loaves this morning. Trading for eggs, coffee, or an hour of help patching my greenhouse.",
    action: "I Can Help",
    actionCount: 4,
    createdAt: "2026-08-30T03:40:00Z",
  },
  {
    id: "p14",
    author: "Ines V.",
    householdId: "HH-0455",
    island: "Cedar Cove",
    scope: "my-isle",
    tag: "ResourceOffer",
    title: "Lending our generator, evenings only",
    body: "1.8kW, quiet-ish. Free to borrow 18:00\u201322:00 if you bring your own fuel. Priority to households with medical gear.",
    action: "I Can Help",
    actionCount: 13,
    createdAt: "2026-08-29T20:15:00Z",
  },
  {
    id: "p15",
    author: "Marcus D.",
    householdId: "HH-0781",
    island: "Cedar Cove",
    scope: "my-isle",
    tag: "RideShare",
    title: "Skiff crossing to Driftwood, 14:00",
    body: "Running the small skiff over for a parts pickup. One passenger seat, or I can carry a package under 20kg.",
    action: "Hop on Boat",
    actionCount: 3,
    image: "/posts/boat.png",
    createdAt: "2026-08-29T16:00:00Z",
  },
  {
    id: "p16",
    author: "Priya M.",
    householdId: "HH-3310",
    island: "Driftwood Atoll",
    scope: "archipelago",
    tag: "FairShare",
    title: "Sharing our storm-kit surplus",
    body: "Twenty spare kits after our allocation round. Offering them to any isle short before the next front lands.",
    action: "Claim Allocation",
    actionCount: 22,
    createdAt: "2026-08-30T04:10:00Z",
    comments: [
      { id: "c11", author: "Sofia N.", body: "Saltwind would take six if the channel stays calm.", createdAt: "2026-08-30T04:48:00Z" },
      { id: "c12", author: "Elena R.", body: "Cedar Cove could collect on the Thursday run.", createdAt: "2026-08-30T05:30:00Z" },
    ],
  },
  {
    id: "p17",
    author: "Tama R.",
    householdId: "HH-5502",
    island: "Saltwind Cay",
    scope: "archipelago",
    tag: "ResourceOffer",
    title: "Solar controllers, 3 spare",
    body: "Upgraded our array and have three 30A MPPT controllers going free. Would rather they work than sit in a crate.",
    action: "I Can Help",
    actionCount: 7,
    createdAt: "2026-08-29T21:25:00Z",
  },
  {
    id: "p18",
    author: "Lena F.",
    householdId: "HH-6120",
    island: "Farreach Isle",
    scope: "archipelago",
    tag: "HazardAlert",
    title: "Fuel slick, north channel",
    body: "Thin sheen roughly two nm off the north head, drifting east. Avoid drawing seawater for filtration until it clears.",
    action: "I Can Help",
    actionCount: 15,
    image: "/posts/hazard.png",
    createdAt: "2026-08-30T02:55:00Z",
    isUrgent: true,
    comments: [
      { id: "c13", author: "Keoni L.", body: "Booms deployed on our side as a precaution.", createdAt: "2026-08-30T03:40:00Z" },
    ],
  },
  {
    id: "p19",
    author: "Otto B.",
    householdId: "HH-8801",
    island: "Driftwood Atoll",
    scope: "archipelago",
    tag: "RideShare",
    title: "Supply boat, Thursday circuit",
    body: "Running the full circuit Thursday: Driftwood, Cedar Cove, Saltwind, back. Cargo space for four pallets total.",
    action: "Hop on Boat",
    actionCount: 9,
    image: "/posts/boat.png",
    createdAt: "2026-08-29T14:20:00Z",
  },
  {
    id: "p20",
    author: "Yui N.",
    householdId: "HH-9043",
    island: "Farreach Isle",
    scope: "archipelago",
    tag: "LocalMarket",
    title: "Seed swap \u2014 salt-tolerant varieties",
    body: "Sea kale, samphire and a hardy chard that survived last season. Bring anything that grows in brackish soil.",
    action: "I Can Help",
    actionCount: 12,
    createdAt: "2026-08-29T11:05:00Z",
    comments: [
      { id: "c14", author: "Mara K.", body: "Bringing cedar cuttings and two jars of kelp seed.", createdAt: "2026-08-29T12:10:00Z" },
    ],
  },
  {
    id: "p21",
    author: "Halima S.",
    householdId: "HH-7215",
    island: "Saltwind Cay",
    scope: "archipelago",
    tag: "ResourceOffer",
    title: "Desalination spares, free to a good isle",
    body: "Membranes and two pressure valves from the old unit. Documented and tested. Will crate them for any passing boat.",
    action: "I Can Help",
    actionCount: 5,
    createdAt: "2026-08-29T09:30:00Z",
  },
  {
    id: "p22",
    author: "Diego C.",
    householdId: "HH-4488",
    island: "Driftwood Atoll",
    scope: "archipelago",
    tag: "FairShare",
    title: "Fuel rationing starts Monday",
    body: "Tanker slipped a week. Council set 15L per household until it docks. Medical and fishing vessels exempt.",
    action: "Claim Allocation",
    actionCount: 28,
    createdAt: "2026-08-29T07:45:00Z",
  },
];

export const tideLogs: TideLog[] = [
  {
    id: "t1",
    author: "Dock Crew",
    label: "Morning catch",
    mediaType: "photo",
    createdAt: "2026-08-30T06:00:00Z",
    expiresAt: "2026-08-31T06:00:00Z",
    preview: "\ud83d\udc1f",
    caption: "Forty kilos of silver hake landed at Dock 2. First come from 07:00.",
    island: "Cedar Cove",
    photo: "/posts/salmon.png",
  },
  {
    id: "t2",
    author: "Mara K.",
    label: "Water clarity",
    mediaType: "photo",
    createdAt: "2026-08-30T08:00:00Z",
    expiresAt: "2026-08-31T08:00:00Z",
    preview: "\ud83c\udf0a",
    caption: "Visibility back to about four metres off the point. Silt has finally settled.",
    island: "Cedar Cove",
    photo: "/posts/clarity.png",
  },
  {
    id: "t3",
    author: "Storm Watch",
    label: "Dock damage",
    mediaType: "video",
    createdAt: "2026-08-30T07:40:00Z",
    expiresAt: "2026-08-31T07:40:00Z",
    preview: "\u26a0\ufe0f",
    caption: "West finger of Dock 3 lost two planks overnight. Repair party forming at low tide.",
    island: "Cedar Cove",
    photo: "/posts/hazard.png",
  },
  {
    id: "t4",
    author: "Elena R.",
    label: "Ferry ETA",
    mediaType: "text",
    createdAt: "2026-08-30T12:00:00Z",
    expiresAt: "2026-08-31T12:00:00Z",
    preview: "\ud83d\udea2",
    caption: "Mainland ferry pushed to 15:40. Allocation pickup shifts with it.",
    island: "Cedar Cove",
    photo: "/posts/boat.png",
  },
  {
    id: "t5",
    author: "Hana W.",
    label: "Market open",
    mediaType: "photo",
    createdAt: "2026-08-30T09:00:00Z",
    expiresAt: "2026-08-31T09:00:00Z",
    preview: "\ud83d\uded2",
    caption: "Smoker is going and the shed is open. Barter as welcome as cash.",
    island: "Cedar Cove",
    photo: "/posts/market.png",
  },
  {
    id: "t6",
    author: "Keoni L.",
    label: "Channel swell",
    mediaType: "video",
    createdAt: "2026-08-30T10:30:00Z",
    expiresAt: "2026-08-31T10:30:00Z",
    preview: "\u26f5",
    caption: "Mid-channel running about a metre. Fine for the bigger hulls, rough in a skiff.",
    island: "Driftwood Atoll",
    photo: "/posts/swell.png",
  },
  {
    id: "t7",
    author: "Sofia N.",
    label: "South landing",
    mediaType: "photo",
    createdAt: "2026-08-30T11:15:00Z",
    expiresAt: "2026-08-31T11:15:00Z",
    preview: "\ud83c\udfd6\ufe0f",
    caption: "Erosion has taken another half metre of the approach. East cove until further notice.",
    island: "Saltwind Cay",
    photo: "/posts/erosion.png",
  },
];

export const islands: Island[] = [
  {
    id: "i1",
    name: "Cedar Cove",
    lat: 48.5,
    lng: -123.2,
    status: "event",
    distanceNm: 0,
    isHome: true,
    description: "Your home island — active micro-market today",
    needs: ["Generator spark plugs", "Dock timber"],
    offers: ["Smoked fish", "Workshop tools"],
    households: 84,
  },
  {
    id: "i2",
    name: "Driftwood Atoll",
    lat: 48.7,
    lng: -122.9,
    status: "surplus",
    distanceNm: 14,
    description: "Water filter surplus — open to trade",
    needs: ["Diesel", "Boat parts"],
    offers: ["Water filters ×12", "Storm kits ×20"],
    households: 61,
  },
  {
    id: "i3",
    name: "Saltwind Cay",
    lat: 48.3,
    lng: -123.5,
    status: "urgent",
    distanceNm: 22,
    description: "Urgent need: generator parts, dock repairs underway",
    needs: ["Generator parts", "Sandbags"],
    offers: ["Fresh catch (40 lbs)", "Rope & rigging"],
    households: 47,
  },
  {
    id: "i4",
    name: "Farreach Isle",
    lat: 48.9,
    lng: -123.8,
    status: "event",
    distanceNm: 31,
    description: "Sister-island knowledge share on saltwater farming",
    needs: ["Kelp farming starter kit"],
    offers: ["Saltwater farming know-how", "Wildflower honey"],
    households: 38,
  },
  {
    id: "i5",
    name: "Mist Harbor",
    lat: 48.1,
    lng: -122.7,
    status: "surplus",
    distanceNm: 18,
    description: "Fresh harvest surplus — root vegetables & greens",
    needs: ["Cold storage"],
    offers: ["Root vegetables", "Greens & herbs"],
    households: 52,
  },
];

export const sisterIslands: Island[] = [
  {
    id: "s1",
    name: "Funafuti",
    lat: -8.52,
    lng: 179.2,
    status: "urgent",
    distanceNm: 5400,
    description: "Sharing sea-wall designs after three king tides this season.",
    isSister: true,
    region: "Tuvalu · Pacific",
    needs: ["Sea-wall materials"],
    offers: ["King-tide defence designs"],
    households: 620,
  },
  {
    id: "s2",
    name: "Great Exuma",
    lat: 23.5,
    lng: -75.8,
    status: "surplus",
    distanceNm: 2900,
    description: "Surplus solar controllers and a decade of hurricane know-how.",
    isSister: true,
    region: "Bahamas · Caribbean",
    needs: ["Nothing urgent"],
    offers: ["Solar controllers ×3", "Hurricane playbook"],
    households: 410,
  },
  {
    id: "s3",
    name: "Faial",
    lat: 38.58,
    lng: -28.7,
    status: "event",
    distanceNm: 4100,
    description: "Hosting this week's erosion-control exchange.",
    isSister: true,
    region: "Azores · Atlantic",
    needs: ["Volunteers for the survey"],
    offers: ["Erosion-control methods"],
    households: 290,
  },
  {
    id: "s4",
    name: "Isle of Lewis",
    lat: 58.2,
    lng: -6.4,
    status: "surplus",
    distanceNm: 3900,
    description: "Peat-fired district heat and community wind, freely documented.",
    isSister: true,
    region: "Outer Hebrides · Scotland",
    needs: ["Nothing urgent"],
    offers: ["Community wind schematics", "Peat district heat"],
    households: 180,
  },
  {
    id: "s5",
    name: "Malé Atoll",
    lat: 4.17,
    lng: 73.5,
    status: "urgent",
    distanceNm: 7300,
    description: "Seeking desalination membranes before the dry season.",
    isSister: true,
    region: "Maldives · Indian Ocean",
    needs: ["Desalination membranes"],
    offers: ["Reef nursery protocol"],
    households: 1300,
  },
  {
    id: "s6",
    name: "Espiritu Santo",
    lat: -15.37,
    lng: 166.96,
    status: "event",
    distanceNm: 6100,
    description: "Saltwater farming trials, second harvest reported.",
    isSister: true,
    region: "Vanuatu · Pacific",
    needs: ["Seed stock"],
    offers: ["Saltwater farming trial data"],
    households: 240,
  },
];

export const tradeRequests: TradeRequest[] = [
  {
    id: "tr1",
    fromIsland: "Cedar Cove",
    toIsland: "Driftwood Atoll",
    offering: "15L diesel + smoked fish",
    seeking: "4× water filters",
    status: "negotiating",
  },
  {
    id: "tr2",
    fromIsland: "Saltwind Cay",
    toIsland: "Cedar Cove",
    offering: "Fresh catch (40 lbs)",
    seeking: "Generator spark plugs",
    status: "open",
  },
  {
    id: "tr3",
    fromIsland: "Mist Harbor",
    toIsland: "Farreach Isle",
    offering: "Root vegetable crate",
    seeking: "Kelp farming starter kit",
    status: "scheduled",
  },
];

export const directory: DirectoryEntry[] = [
  {
    id: "d1",
    category: "business",
    name: "Cove General Store",
    description: "Dry goods, hardware, mail hold",
    contact: "Dock 1 — open 8am–6pm",
    available: true,
    photo: "/posts/supplies.png",
  },
  {
    id: "d2",
    category: "food",
    name: "Hana's Smokehouse",
    description: "Smoked salmon, kelp wraps — daily catch",
    contact: "Old fish shed",
    available: true,
    photo: "/posts/salmon.png",
  },
  {
    id: "d3",
    category: "ride",
    name: "Tui's Truck Share",
    description: "Mainland supply runs — weekends",
    contact: "HH-0550 via app",
    available: true,
    photo: "/posts/diesel.png",
  },
  {
    id: "d4",
    category: "artisan",
    name: "Mara's Rope Works",
    description: "Net repair, custom rigging, dock lines",
    contact: "Workshop behind marina",
    available: false,
    photo: "/posts/boat.png",
  },
  {
    id: "d5",
    category: "food",
    name: "Community Garden Stand",
    description: "Seasonal greens, herbs, honey",
    contact: "High-Ground Hub",
    available: true,
    photo: "/posts/market.png",
  },
];

export const allocations: Allocation[] = [
  {
    id: "a1",
    item: "Emergency Water (cases)",
    quota: 4,
    reserved: 2,
    unit: "cases",
    arrivalEta: "Aug 31, 2pm",
  },
  {
    id: "a2",
    item: "Storm Kit",
    quota: 1,
    reserved: 0,
    unit: "kit",
    arrivalEta: "Aug 31, 2pm",
  },
  {
    id: "a3",
    item: "Fuel Ration",
    quota: 40,
    reserved: 40,
    unit: "liters",
  },
];

export const gearExchange: GearItem[] = [
  {
    id: "g1",
    name: "Honda EU2200i Generator",
    owner: "Jonas P. (HH-0871)",
    condition: "Good — serviced last month",
    availableUntil: "Sep 15",
  },
  {
    id: "g2",
    name: "Commercial Debris Net (50ft)",
    owner: "Dock Crew",
    condition: "Fair — one patch",
    availableUntil: "Sep 30",
  },
  {
    id: "g3",
    name: "Kayak + Paddles (2-person)",
    owner: "Elena R. (HH-1203)",
    condition: "Excellent",
    availableUntil: "Aug 31",
  },
];

export const workParties: WorkParty[] = [
  {
    id: "w1",
    title: "North Trail Line Clearance",
    location: "Cedar Grove footpath",
    date: "Aug 30, 11am",
    volunteersNeeded: 6,
    volunteersSigned: 4,
  },
  {
    id: "w2",
    title: "Dock Plank Replacement",
    location: "Main Dock, Bay 2",
    date: "Aug 31, 9am",
    volunteersNeeded: 8,
    volunteersSigned: 3,
  },
  {
    id: "w3",
    title: "Debris Sweep — East Cove",
    location: "East Cove beach",
    date: "Sep 1, 8am",
    volunteersNeeded: 12,
    volunteersSigned: 7,
  },
];

export const microMarkets: MicroMarket[] = [
  {
    id: "m1",
    vendor: "Hana W.",
    items: "Smoked salmon, kelp wraps",
    location: "Old fish shed",
    until: "6pm today",
  },
  {
    id: "m2",
    vendor: "Community Garden",
    items: "Kale, herbs, wildflower honey",
    location: "High-Ground Hub",
    until: "4pm today",
  },
];

export const badges: Badge[] = [
  {
    id: "b1",
    name: "Captain",
    description: "Water transport volunteer",
    icon: "⚓",
  },
  {
    id: "b2",
    name: "Guardian",
    description: "Event organizer",
    icon: "🛡️",
  },
  {
    id: "b3",
    name: "Harvester",
    description: "Food & catch contributor",
    icon: "🌾",
  },
];

export const boatTrips: BoatTrip[] = [
  {
    id: "bt1",
    captain: "Keoni L.",
    vessel: "Sea Sparrow (28ft)",
    route: "Cedar Cove → Driftwood Atoll",
    departure: "Aug 31, 7am",
    seats: 4,
    seatsTaken: 2,
    type: "passenger",
  },
  {
    id: "bt2",
    captain: "Mara K.",
    vessel: "Northwind (skiff)",
    route: "Cedar Cove → Port Alton",
    departure: "Aug 31, 6am",
    seats: 2,
    seatsTaken: 1,
    type: "supply",
  },
  {
    id: "bt3",
    captain: "Tui M.",
    vessel: "Harbor Queen (40ft)",
    route: "Cedar Cove → Saltwind Cay",
    departure: "Sep 1, 8am",
    seats: 6,
    seatsTaken: 0,
    type: "passenger",
  },
];

export const weatherAlerts: WeatherAlert[] = [
  {
    id: "wa1",
    type: "tide",
    message:
      "High Tide Alert: Distribution moved to High-Ground Hub. Main dock inaccessible 11am–2pm.",
    severity: "warning",
    validUntil: "Aug 30, 2pm",
  },
  {
    id: "wa2",
    type: "wind",
    message: "SW winds 25–30kt this afternoon. Small craft advisory in effect.",
    severity: "info",
    validUntil: "Aug 30, 6pm",
  },
];

export const CURRENT_HOUSEHOLD_ID = "HH-1042";

export const initialIslandDistress: IslandDistress[] = [
  {
    islandId: "i3",
    islandName: "Saltwind Cay",
    reason: "Water contamination detected — main cistern compromised",
    activatedBy: "Island Council",
    activatedAt: "2026-08-30T06:30:00Z",
  },
];

export const initialHazardPins: HazardPin[] = [
  {
    id: "h1",
    type: "infrastructure",
    category: "Fallen Tree",
    lat: 48.502,
    lng: -123.198,
    x: 35,
    y: 42,
    description: "Large palm down on roof at 12 Cedar Lane — access blocked",
    reportedBy: "Jonas P.",
    createdAt: "2026-08-30T07:40:00Z",
    severity: "critical",
    hasPhoto: true,
  },
  {
    id: "h2",
    type: "infrastructure",
    category: "Sea Wall Damage",
    lat: 48.498,
    lng: -123.205,
    x: 62,
    y: 28,
    description: "South sea wall breach — 3m section collapsed overnight",
    reportedBy: "Dock Crew",
    createdAt: "2026-08-30T05:15:00Z",
    severity: "medium",
    hasPhoto: true,
  },
  {
    id: "h3",
    type: "infrastructure",
    category: "Blocked Road",
    lat: 48.505,
    lng: -123.192,
    x: 48,
    y: 65,
    description: "North Trail impassable — downed power line across path",
    reportedBy: "Mara K.",
    createdAt: "2026-08-30T07:40:00Z",
    severity: "critical",
    hasPhoto: false,
  },
  {
    id: "h4",
    type: "ecological",
    category: "Ocean Discoloration",
    lat: 48.496,
    lng: -123.210,
    x: 78,
    y: 55,
    description: "Dark tide patch 200m off east cove — possible algae bloom",
    reportedBy: "Elena R.",
    createdAt: "2026-08-30T09:10:00Z",
    severity: "medium",
    hasPhoto: true,
  },
];

export const emergencyResponders: EmergencyResponder[] = [
  {
    id: "r1",
    name: "Dr. Amara Chen",
    role: "doctor",
    distanceM: 420,
    available: true,
  },
  {
    id: "r2",
    name: "Keoni L.",
    role: "boat",
    distanceM: 180,
    available: true,
  },
  {
    id: "r3",
    name: "First Aid — Dock Station",
    role: "first-aid",
    distanceM: 310,
    available: true,
  },
  {
    id: "r4",
    name: "Elena R. (Council)",
    role: "leader",
    distanceM: 550,
    available: true,
  },
];

/** Live conditions shown in the Active Island widget. */
export interface IslandConditions {
  island: string;
  nextHighTide: string;
  tideHeightM: number;
  windKt: number;
  windDir: string;
  swellM: number;
  summary: string;
}

export const islandConditions: IslandConditions = {
  island: HOME_ISLAND,
  nextHighTide: "15:42",
  tideHeightM: 3.4,
  windKt: 18,
  windDir: "SW",
  swellM: 1.2,
  summary: "Choppy in the channel, easing after dusk",
};

export const bookmarkedIslands = [
  { id: "i1", name: "Cedar Cove", status: "event" as const },
  { id: "i3", name: "Saltwind Cay", status: "urgent" as const },
  { id: "i2", name: "Driftwood Atoll", status: "surplus" as const },
];
