import type {
  Allocation,
  Badge,
  BoatTrip,
  DirectoryEntry,
  EmergencyResponder,
  GearItem,
  HazardPin,
  Island,
  IslandDistress,
  MicroMarket,
  Post,
  TideLog,
  TradeRequest,
  WeatherAlert,
  WorkParty,
} from "./types";

export const HOME_ISLAND = "Cedar Cove";

export const posts: Post[] = [
  {
    id: "p1",
    author: "Mara K.",
    householdId: "HH-1042",
    island: "Cedar Cove",
    scope: "my-isle",
    tag: "ResourceOffer",
    title: "Extra diesel — 20L available",
    body: "Storm generator ran less than expected. Diesel in sealed jerry cans at Dock 2. First come for neighbors only.",
    action: "I Can Help",
    actionCount: 3,
    createdAt: "2026-08-30T08:15:00Z",
  },
  {
    id: "p2",
    author: "Jonas P.",
    householdId: "HH-0871",
    island: "Cedar Cove",
    scope: "my-isle",
    tag: "HazardAlert",
    title: "Downed line on North Trail",
    body: "Power line across footpath near the cedar grove. Avoid until utility crew clears — ETA noon.",
    action: "I Can Help",
    actionCount: 7,
    createdAt: "2026-08-30T07:40:00Z",
    isUrgent: true,
  },
  {
    id: "p3",
    author: "Elena R.",
    householdId: "HH-1203",
    island: "Cedar Cove",
    scope: "my-isle",
    tag: "FairShare",
    title: "Storm kit allocation open",
    body: "Households HH-1000–HH-1300 can reserve one storm kit per family. Pickup at High-Ground Hub when ferry docks.",
    action: "Claim Allocation",
    actionCount: 12,
    createdAt: "2026-08-30T06:00:00Z",
  },
  {
    id: "p4",
    author: "Tui M.",
    householdId: "HH-0550",
    island: "Cedar Cove",
    scope: "my-isle",
    tag: "RideShare",
    title: "Truck run to mainland Saturday",
    body: "Heading to Port Alton for supplies. Two cargo spots and one passenger seat. Return Sunday AM.",
    action: "Hop on Boat",
    actionCount: 2,
    createdAt: "2026-08-29T18:30:00Z",
  },
  {
    id: "p5",
    author: "Hana W.",
    householdId: "HH-0334",
    island: "Cedar Cove",
    scope: "my-isle",
    tag: "LocalMarket",
    title: "Smoked salmon — dockside today",
    body: "Fresh catch smoked this morning. $18/lb at the old fish shed. Barter welcome for firewood.",
    action: "I Can Help",
    actionCount: 5,
    createdAt: "2026-08-30T09:00:00Z",
  },
  {
    id: "p6",
    author: "Keoni L.",
    householdId: "HH-2201",
    island: "Driftwood Atoll",
    scope: "archipelago",
    tag: "ResourceOffer",
    title: "Water filters surplus (12 units)",
    body: "Our shipment doubled. Happy to trade for fuel or boat parts. Can meet mid-channel Thursday.",
    action: "I Can Help",
    actionCount: 4,
    createdAt: "2026-08-30T05:20:00Z",
  },
  {
    id: "p7",
    author: "Sofia N.",
    householdId: "HH-4410",
    island: "Saltwind Cay",
    scope: "archipelago",
    tag: "HazardAlert",
    title: "Erosion at south landing",
    body: "South dock approach washed out overnight. Use east cove until repairs complete.",
    action: "I Can Help",
    actionCount: 9,
    createdAt: "2026-08-29T22:10:00Z",
    isUrgent: true,
  },
  {
    id: "p8",
    author: "Ravi S.",
    householdId: "HH-7788",
    island: "Farreach Isle",
    scope: "archipelago",
    tag: "LocalMarket",
    title: "Micro-market: honey & herbs",
    body: "Pop-up at community hall steps. Wildflower honey, dried kelp seasoning. Today until 4pm.",
    action: "I Can Help",
    actionCount: 1,
    createdAt: "2026-08-30T10:00:00Z",
  },
];

export const tideLogs: TideLog[] = [
  {
    id: "t1",
    author: "Dock Crew",
    label: "Morning catch",
    mediaType: "photo",
    expiresAt: "2026-08-31T06:00:00Z",
    preview: "🐟",
  },
  {
    id: "t2",
    author: "Mara K.",
    label: "Water clarity",
    mediaType: "photo",
    expiresAt: "2026-08-31T08:00:00Z",
    preview: "🌊",
  },
  {
    id: "t3",
    author: "Storm Watch",
    label: "Dock damage",
    mediaType: "video",
    expiresAt: "2026-08-31T07:40:00Z",
    preview: "⚠️",
  },
  {
    id: "t4",
    author: "Elena R.",
    label: "Ferry ETA",
    mediaType: "text",
    expiresAt: "2026-08-31T12:00:00Z",
    preview: "🚢",
  },
  {
    id: "t5",
    author: "Hana W.",
    label: "Market open",
    mediaType: "photo",
    expiresAt: "2026-08-31T09:00:00Z",
    preview: "🛒",
  },
];

export const islands: Island[] = [
  {
    id: "i1",
    name: "Cedar Cove",
    lat: 48.5,
    lng: -123.2,
    status: "event",
    distanceNm: 0,
    isHome: true,
    description: "Your home island — active micro-market today",
  },
  {
    id: "i2",
    name: "Driftwood Atoll",
    lat: 48.7,
    lng: -122.9,
    status: "surplus",
    distanceNm: 14,
    description: "Water filter surplus — open to trade",
  },
  {
    id: "i3",
    name: "Saltwind Cay",
    lat: 48.3,
    lng: -123.5,
    status: "urgent",
    distanceNm: 22,
    description: "Urgent need: generator parts, dock repairs underway",
  },
  {
    id: "i4",
    name: "Farreach Isle",
    lat: 48.9,
    lng: -123.8,
    status: "event",
    distanceNm: 31,
    description: "Sister-island knowledge share on saltwater farming",
  },
  {
    id: "i5",
    name: "Mist Harbor",
    lat: 48.1,
    lng: -122.7,
    status: "surplus",
    distanceNm: 18,
    description: "Fresh harvest surplus — root vegetables & greens",
  },
];

export const tradeRequests: TradeRequest[] = [
  {
    id: "tr1",
    fromIsland: "Cedar Cove",
    toIsland: "Driftwood Atoll",
    offering: "15L diesel + smoked fish",
    seeking: "4× water filters",
    status: "negotiating",
  },
  {
    id: "tr2",
    fromIsland: "Saltwind Cay",
    toIsland: "Cedar Cove",
    offering: "Fresh catch (40 lbs)",
    seeking: "Generator spark plugs",
    status: "open",
  },
  {
    id: "tr3",
    fromIsland: "Mist Harbor",
    toIsland: "Farreach Isle",
    offering: "Root vegetable crate",
    seeking: "Kelp farming starter kit",
    status: "scheduled",
  },
];

export const directory: DirectoryEntry[] = [
  {
    id: "d1",
    category: "business",
    name: "Cove General Store",
    description: "Dry goods, hardware, mail hold",
    contact: "Dock 1 — open 8am–6pm",
    available: true,
  },
  {
    id: "d2",
    category: "food",
    name: "Hana's Smokehouse",
    description: "Smoked salmon, kelp wraps — daily catch",
    contact: "Old fish shed",
    available: true,
  },
  {
    id: "d3",
    category: "ride",
    name: "Tui's Truck Share",
    description: "Mainland supply runs — weekends",
    contact: "HH-0550 via app",
    available: true,
  },
  {
    id: "d4",
    category: "artisan",
    name: "Mara's Rope Works",
    description: "Net repair, custom rigging, dock lines",
    contact: "Workshop behind marina",
    available: false,
  },
  {
    id: "d5",
    category: "food",
    name: "Community Garden Stand",
    description: "Seasonal greens, herbs, honey",
    contact: "High-Ground Hub",
    available: true,
  },
];

export const allocations: Allocation[] = [
  {
    id: "a1",
    item: "Emergency Water (cases)",
    quota: 4,
    reserved: 2,
    unit: "cases",
    arrivalEta: "Aug 31, 2pm",
  },
  {
    id: "a2",
    item: "Storm Kit",
    quota: 1,
    reserved: 0,
    unit: "kit",
    arrivalEta: "Aug 31, 2pm",
  },
  {
    id: "a3",
    item: "Fuel Ration",
    quota: 40,
    reserved: 40,
    unit: "liters",
  },
];

export const gearExchange: GearItem[] = [
  {
    id: "g1",
    name: "Honda EU2200i Generator",
    owner: "Jonas P. (HH-0871)",
    condition: "Good — serviced last month",
    availableUntil: "Sep 15",
  },
  {
    id: "g2",
    name: "Commercial Debris Net (50ft)",
    owner: "Dock Crew",
    condition: "Fair — one patch",
    availableUntil: "Sep 30",
  },
  {
    id: "g3",
    name: "Kayak + Paddles (2-person)",
    owner: "Elena R. (HH-1203)",
    condition: "Excellent",
    availableUntil: "Aug 31",
  },
];

export const workParties: WorkParty[] = [
  {
    id: "w1",
    title: "North Trail Line Clearance",
    location: "Cedar Grove footpath",
    date: "Aug 30, 11am",
    volunteersNeeded: 6,
    volunteersSigned: 4,
  },
  {
    id: "w2",
    title: "Dock Plank Replacement",
    location: "Main Dock, Bay 2",
    date: "Aug 31, 9am",
    volunteersNeeded: 8,
    volunteersSigned: 3,
  },
  {
    id: "w3",
    title: "Debris Sweep — East Cove",
    location: "East Cove beach",
    date: "Sep 1, 8am",
    volunteersNeeded: 12,
    volunteersSigned: 7,
  },
];

export const microMarkets: MicroMarket[] = [
  {
    id: "m1",
    vendor: "Hana W.",
    items: "Smoked salmon, kelp wraps",
    location: "Old fish shed",
    until: "6pm today",
  },
  {
    id: "m2",
    vendor: "Community Garden",
    items: "Kale, herbs, wildflower honey",
    location: "High-Ground Hub",
    until: "4pm today",
  },
];

export const badges: Badge[] = [
  {
    id: "b1",
    name: "Captain",
    description: "Water transport volunteer",
    icon: "⚓",
  },
  {
    id: "b2",
    name: "Guardian",
    description: "Event organizer",
    icon: "🛡️",
  },
  {
    id: "b3",
    name: "Harvester",
    description: "Food & catch contributor",
    icon: "🌾",
  },
];

export const boatTrips: BoatTrip[] = [
  {
    id: "bt1",
    captain: "Keoni L.",
    vessel: "Sea Sparrow (28ft)",
    route: "Cedar Cove → Driftwood Atoll",
    departure: "Aug 31, 7am",
    seats: 4,
    seatsTaken: 2,
    type: "passenger",
  },
  {
    id: "bt2",
    captain: "Mara K.",
    vessel: "Northwind (skiff)",
    route: "Cedar Cove → Port Alton",
    departure: "Aug 31, 6am",
    seats: 2,
    seatsTaken: 1,
    type: "supply",
  },
  {
    id: "bt3",
    captain: "Tui M.",
    vessel: "Harbor Queen (40ft)",
    route: "Cedar Cove → Saltwind Cay",
    departure: "Sep 1, 8am",
    seats: 6,
    seatsTaken: 0,
    type: "passenger",
  },
];

export const weatherAlerts: WeatherAlert[] = [
  {
    id: "wa1",
    type: "tide",
    message:
      "High Tide Alert: Distribution moved to High-Ground Hub. Main dock inaccessible 11am–2pm.",
    severity: "warning",
    validUntil: "Aug 30, 2pm",
  },
  {
    id: "wa2",
    type: "wind",
    message: "SW winds 25–30kt this afternoon. Small craft advisory in effect.",
    severity: "info",
    validUntil: "Aug 30, 6pm",
  },
];

export const CURRENT_HOUSEHOLD_ID = "HH-1042";

export const initialIslandDistress: IslandDistress[] = [
  {
    islandId: "i3",
    islandName: "Saltwind Cay",
    reason: "Water contamination detected — main cistern compromised",
    activatedBy: "Island Council",
    activatedAt: "2026-08-30T06:30:00Z",
  },
];

export const initialHazardPins: HazardPin[] = [
  {
    id: "h1",
    type: "infrastructure",
    category: "Fallen Tree",
    lat: 48.502,
    lng: -123.198,
    x: 35,
    y: 42,
    description: "Large palm down on roof at 12 Cedar Lane — access blocked",
    reportedBy: "Jonas P.",
    createdAt: "2026-08-30T07:40:00Z",
    severity: "critical",
    hasPhoto: true,
  },
  {
    id: "h2",
    type: "infrastructure",
    category: "Sea Wall Damage",
    lat: 48.498,
    lng: -123.205,
    x: 62,
    y: 28,
    description: "South sea wall breach — 3m section collapsed overnight",
    reportedBy: "Dock Crew",
    createdAt: "2026-08-30T05:15:00Z",
    severity: "medium",
    hasPhoto: true,
  },
  {
    id: "h3",
    type: "infrastructure",
    category: "Blocked Road",
    lat: 48.505,
    lng: -123.192,
    x: 48,
    y: 65,
    description: "North Trail impassable — downed power line across path",
    reportedBy: "Mara K.",
    createdAt: "2026-08-30T07:40:00Z",
    severity: "critical",
    hasPhoto: false,
  },
  {
    id: "h4",
    type: "ecological",
    category: "Ocean Discoloration",
    lat: 48.496,
    lng: -123.210,
    x: 78,
    y: 55,
    description: "Dark tide patch 200m off east cove — possible algae bloom",
    reportedBy: "Elena R.",
    createdAt: "2026-08-30T09:10:00Z",
    severity: "medium",
    hasPhoto: true,
  },
];

export const emergencyResponders: EmergencyResponder[] = [
  {
    id: "r1",
    name: "Dr. Amara Chen",
    role: "doctor",
    distanceM: 420,
    available: true,
  },
  {
    id: "r2",
    name: "Keoni L.",
    role: "boat",
    distanceM: 180,
    available: true,
  },
  {
    id: "r3",
    name: "First Aid — Dock Station",
    role: "first-aid",
    distanceM: 310,
    available: true,
  },
  {
    id: "r4",
    name: "Elena R. (Council)",
    role: "leader",
    distanceM: 550,
    available: true,
  },
];
